### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by RyUp1** [mholgatem/gpioneer#12]
Will this work with a psp joystick? Also... this might be a dumb question..but how do I access the web interface to configure buttons? I saw something about the IP address but I have no idea what to do. Thanks!

**Comment by mholgatem** [comment]
as long as the joystick is activating gpio's, then it will work. Raspberry pi gpio's are digitial, rather than analogue; so pressing a direction a little bit vs. all the way results in the same press. 

The web interface is accessible through a web browser on any computer that is connected to the same network. Just type in the ip address of your raspberry pi.
