### ISSUE TITLE
2P Controls

### ISSUE THREAD

**Issue by lemmons11** [mholgatem/gpioneer#7]
Hello,

First off thanks for the driver, I got it working fairly quickly (the website is a very nice feature).

One issue I am having is trying to get a two player system working. Is this within the scope of your driver? Or am I just being a noob?

I am using a PI 3, trying to make a 2 player cocktail style. As mentioned I have all of the 1 player functions working fine but not the 2 player (or a way to rotate the screen 180 degrees but I digress).

Any information you can send my way would be much appreciated.

Aaron

**Comment by mholgatem** [comment]
So, as of right now, GPioneer just registers as a single keyboard device; but you can set it up for two players. 

> First, make sure that you configure all of the controls for both players in GPioneer (here's how to do it if you haven't already)
> 
> - use `sudo python ~/gpioneer/GPioneer.py -c` to manually run config tool
> - when it asks if you'd like to set up another controller, say yes. 

Afterwards, you need to follow [this tutorial](https://www.reddit.com/r/RetroPie/comments/5elgqq/how_to_get_two_keyboards_controlling_two/). I am currently working on the next generation GPioneer, which will register each player as their own HID device.

**Comment by lemmons11** [comment]
I've taken your advice and done the following steps:

sudo python ~/gpioneer/GPioneer.py -c

**set up controllers 1 and 2 

cd /opt/retropie/configs/all/

cp retroarch.cfg retroarch.cfg.bak

nano retroarch.cfg

input_player1_a = ctrl
input_player1_b = alt
input_player1_y = shift
input_player1_x = space
input_player1_start = num1
input_player1_select = num5
input_player1_l = z
input_player1_r = x
input_player1_left = right
input_player1_right = left
input_player1_up = down
input_player1_down = up

input_player2_a = a
input_player2_b = s
input_player2_y = q
input_player2_x = w
input_player2_start = 2
input_player2_select = 6
input_player2_l = i
input_player2_r = k
input_player2_left = g
input_player2_right = d
input_player2_up = f
input_player2_down = r


I saved and restarted the PI and now most things are not working. I can only get my vertical joystick signal to work. Should I not be able to configure both sets of controls through your website by giving the buttons arbitrary keyboard values?

Any thoughts or suggestions? Do you have one document that can explain the process? I got a bit lost in all of the links.

**Comment by mholgatem** [comment]
Your entries are incorrect.  You are missing the quotes around your key bindings and some of the entries are formatted incorrectly. Each entry should look like this:

> input_player1_a = "a" <--- Note the quotes around the letter a

also, special keys (alt, ctrl, shift) need to be specified left or right, like this:

> input_player1_b = "rshift"

here are the valid keys (kp_ stands for 'keypad'):

>  left, right, up, down, enter, kp_enter, tab, insert, del, end, home,
   rshift, shift, ctrl, alt, space, escape, add, subtract, kp_plus, kp_minus,
   f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12,
   num0, num1, num2, num3, num4, num5, num6, num7, num8, num9, pageup, pagedown,
   keypad0, keypad1, keypad2, keypad3, keypad4, keypad5, keypad6, keypad7, keypad8, keypad9,
   period, capslock, numlock, backspace, multiply, divide, print_screen, scroll_lock,
   tilde, backquote, pause, quote, comma, minus, slash, semicolon, equals, leftbracket,
   backslash, rightbracket, kp_period, kp_equals, rctrl, ralt

here's what a correctly formatted version looks like (you will need to change it based on the keys outputs you have set in gpioneer)

> input_player1_a = "a"
input_player1_b = "b"
input_player1_y = "y"
input_player1_x = "x"
input_player1_start = "t"
input_player1_select = "e"
input_player1_l = "l"
input_player1_r = "r"
input_player1_left = "left"
input_player1_right = "right"
input_player1_up = "up"
input_player1_down = "down"
input_player1_l2 = "d"
input_player1_r2 = "f"
input_player1_l3 = "c"
input_player1_r3 = "v"
>
>input_player2_a = "k"
input_player2_b = "m"
input_player2_y = "o"
input_player2_x = "n"
input_player2_start = "num9"
input_player2_select = "num0"
input_player2_l = "p"
input_player2_r = "q"
input_player2_left = "g"
input_player2_right = "h"
input_player2_up = "i"
input_player2_down = "j"
input_player2_l2 = "s"
input_player2_r2 = "u"
input_player2_l3 = "w"
input_player2_r3 = "z"

**Comment by caver01** [comment]
Lemmons11, Crucially, you don't mention how you have any of your controls configured with GPIOneer which is the whole point. You see, retroarch is an _additional_ configuration that will take your GPIOneer setup and reconfigure things again. It's like taking one config and translating it with another config. It won't help you to troubleshoot GPIOneer setup by adding a retroarch key mapping on top of it.

Maybe you did this, but you need to do one thing at a time and check to verify that the keys you assign to your GPIO PINs are working by themselves, and more to the point, that they are triggered by the switches you think you have wired to them.

One idea is to go into the web interface and assign a key to a control, save and restart, and test it to see if it outputs as expected. For example, if you assign "U" as a command for what you think is wired to UP on your joystick, then go out to a command prompt and press the joystick UP, you should get a "U" to appear on the screen. If not, you know you have it misconfigured or miswired. Keep retroarch out of it for the moment.

Then, once you know the keys that each of your verified switches are generating through GPIOneer, and ONLY THEN, should you setup the mapping in your retroarch.cfg.

I know it's hard advice to hear because it is a lot of extra work, but you will have a very precise result in the end and confidence in what you are doing.

Here's a helpful tidbit for you: You can get the raspberry pi to display your screen upside down (180 degree rotation) by adding the line "display_rotate=2" (without quotes) to your /boot/config.txt file. I run my cocktail arcade system the same way, although I have 4 player controls which was too much for a GPIO solution (using an IPAC4). Still, if I built another system with 2 players I would use GPIOneer for everything.

**Comment by lemmons11** [comment]
First off guys, thanks so much for the patience and the advice! I believe I have it working but would just like to double check.

Using a fresh install, I configured one joystick and one button using GPIOneer. 

![image](https://user-images.githubusercontent.com/29259790/26959938-9ff91306-4c90-11e7-802c-22949664216d.png)

Caver01, at this point you suggest testing the GPIOneer configs using the command prompt. The joystick did NOT seem to work (even though it is mapped to the UP/DOWN/LEFT/RIGHT buttons from the key board, and seen in the previous image).

At this point I thought I'd just try to configure the Retroarch and test from there. 

![image](https://user-images.githubusercontent.com/29259790/26959996-1f34a5d6-4c91-11e7-9fbf-4cf8db7d3a90.png)

I configured Retroarch using the guide that mholgatem provided a link to. One thing I wasn't sure about here is where I have to put these settings. I first edited them here:

/opt/retropie/configs/all/

But the guide also mentioned to put both player 1 and player 2 settings at this location:

/opt/retropie/configs/

Are both locations needed? 

As I mentioned I did get some ROMs working but not others. I am chalking that up to some goofy ROMs but perhaps you guys can see another mistake? 

Thanks again!

**Comment by caver01** [comment]
These questions about retropie are obviously beyond the scope of GPIOneer which is why I was suggesting testing just at the command line. I can tell you that when you edit /opt/retropie/configs/all/retroarch.cfg you are setting up controls for libretro emulators. The config should apply to many different emulators, but you are not really sharing what emulator you are using. It makes a very big difference. For example, if you are using AdvanceMAME, editing these settings will have absolutely no effect because that is a standalone emulator with its own config, but if you are using lr-mame2003 thes settings would apply. You see, there are so many possible ways to use your controls, when you start talking about ROMs not working, it is very hard to give you good advice because we have no idea what exactly you are trying to use.

However, these are exactly the kinds of questions worth asking at the RetroPie forums where I am very active and there are many other users eager to offer help. But I have to warn you that you MUST read the documentation first, and if you do as a question, there is a READ THIS FIRST link that you really need to follow. It will require you to post all of the details about your configuration. If you ignore the advice and skip the documentation (which really does have all of the answers, especially with ROMs) you will draw harsh criticism because you were unwilling to follow the forum rules.

Anyway, it sounds like you are on the right track, but I am surprised that pressing your button doesn't generate a "space" key in any situation.

**Comment by rocket1977** [comment]
Hi Guys,

I have gpioneer installed in a 2 player joystick system, using v4.4 emulation station on a pi.

When I login, player 1 side works perfectly, but player 2 is none responsive.

If I configure input and add player 2 side, then that side works and player 1 side doesn't respond anymore.

I have read your posts and correctly edited the retroarch.cfg (if I change the inputs via emulation station, it simply updates player 1 config inputs in the retroarch.cfg file, yet player 2 config is untouched.

I would have assumed that you can run 2 players via the GPIO pins and there are many pinout diagrams and the web interface shows both 1 & 2 player settings. (attached)

<img width="623" alt="screen shot 2018-05-28 at 11 58 39 pm" src="https://user-images.githubusercontent.com/39699855/40617894-151d4db0-62d3-11e8-9b3e-13205a877de1.png">

Can you think of anything I am doing wrong?

Some success: I installed GPIOnext and both controllers were working! However, player one joystick was on autofire... it would double jump menu items, whilst player 2 side was perfect - both working together.

I must confess I did have Gpioneer installed at the same time, I attempted to run the remove.sh file multiple times, but it came up with error where it couldn't find the web interface folders... so I uninstalled GPIOnext instead.

Any feedback would be appreciated, it would be good to work out a solution... I am using a pi 3b+ if that makes a difference.

Cheers, Shaun.

**Comment by rocket1977** [comment]
![img-1122](https://user-images.githubusercontent.com/39699855/40618342-961f165e-62d4-11e8-8558-da764e87f30d.JPG)
![img-1123](https://user-images.githubusercontent.com/39699855/40618343-965ba01a-62d4-11e8-9a4f-a91903c2a88f.JPG)

sudo bash remove.sh error

**Comment by mholgatem** [comment]
sorry, I just got back from vacation. I'll dig into this in a little bit and get back to you.

Edit:
ok, in command line do the following:
```
cd ~/gpioneer
sudo rm remove.sh
wget https://raw.githubusercontent.com/mholgatem/gpioneer/master/remove.sh
sudo bash remove.sh
```
